storacha/w3cli

bin.js
index.js
test/bin.spec.js

a minimal implementation. The assumption is this command will get more useful once we have [w3accounts](https://github.com/web3-storage/specs/blob/main/w3-account.md)
License: MIT
Signed-off-by: Oli Evans <oli@protocol.ai>

feat: add `whoami` to print agent DID

---

lib.js
test/lib.spec.js

The common path for the first file was set to the entire `path`, not `dirname(path)`. For multiple files the common path ends up as `dirname(path)` but when there's only 1 it stays as `path`, so we end up stripping out the entire path 🤦‍♂️.

fix: missing file name when only single path passed to filesFromPaths

---

bin.js
package.json
shim.js

Using flags in a shebang fails on some systems see https://github.com/web3-storage/w3cli/issues/37
Remove the flag from the shebang. Go back to shimming process.emit, but this time it works. 
**shimmed flavour**
```bash
~/Code/web3-storage/w3cli on main •
❯ ./shim.js up ~/Pictures/behemoth-black-hole-found-in-an-unlikely-place_26209716511_o\~orig.jpeg
1 file (8.4MB)
bagbaieravvyvhoig75tgrvel6cxoqchnsftz4lltduxjckqugmaidmyua2rq
⁂ Stored 1 file
⁂ https://w3s.link/ipfs/bafybeidpouz7j6to2p7ps4j262ii32ov5wnp3rj4slavvsm4dfvonvrc6q
```
Sounds like ESM module load order was the problem last time in #9 
> Since imports in ESM run [async](https://stackoverflow.com/questions/35551366/what-is-the-defined-execution-order-of-es6-imports), we have to make sure that the import runs before all other …

fix: dont error on systems that cant pass flags to env in shebang

---

index.js

fixes #48
I added a test for this, but the issue doesn't happen in our current mock impl. I can spend some more time to make the mock implementation support `--size` and `--cursor` but it's not clear to me that's the right move yet - feels a little like adding extra code just to make a  test fail.

fix: pass cursor to list in `w3 ls`

---

index.js
lib.js
package-lock.json
package.json
test/lib.spec.js

The `files-from-path` module has been updated to do what the code here was doing.
TLDR; web streams and automatic common prefix removal.
More info: https://github.com/web3-storage/files-from-path/pull/23

refactor: use new `files-from-path` module

---

README.md
bin.js
index.js
package-lock.json
package.json

If we're only authorized to act as a single account we shouldn't need to pass an email address to `space register` since we can infer which one to use from the delegations we currently have.
Preserve the ability to pass email using the `--email` option for cases where we are authorized as multiple accounts.
Also add a `--provider` option to `space register` to allow users to register spaces with other providers like NFT.Storage.

feat!: move `space register` email parameter to an `--email` option and add `--provider` option

---

bin.js
test/bin.spec.js

showing an error when users type `w3` is pretty jarring.
Adds a `help [cmd]` command which is set as the `default` so it runs when no command is provided. If it's run with a command that isn't registered it produces the same output as sade would normally (ERROR: Invalid command)
**before (boo, hiss)**
```sh
❯ w3
ERROR
No command specified.
Run `$ w3 --help` for more info.
```
**after**
```sh
❯ ./bin.js
Usage
$ w3 <command> [options]
Available Commands
authorize            Authorize this agent to interact with the w3up service with any capabilities granted to the given email.
up                   Store a file(s) to the service and register an upload.
open                 Open CID on https://w3s.link
ls                   List uploads in the current space
rm                   Remove an …
```

feat: show help text if no cmd

---

README.md

Motivation:
* make it obvious how to use nft.storage
* make it obvious that the default is equivalent to `did:web:web3.storage` and not `web3.storage`

docs: add nft.storage provider example to readme

---

README.md

From https://github.com/sindresorhus/env-paths#pathsconfig - which is the module used by [`conf`](https://www.npmjs.com/package/conf).
closes #6

docs: add FAQ section with conf file location

---

lib.js

This is needed by one of the teams integrating with w3up. 
w3up-client will already fail if you pass a different principal than the store is configured to use, so we don't need to add any extra validation logic - end-users can generate a key with `npx ucan-key ed --json` and set the `W3_PRINCIPAL` environment variable for at least the first invocation of `w3` in a new environment. 
Setting `W3_PRINCIPAL` on subsequent invocations is optional but will ensure the principal used by the client is always the same.

feat: add ability to specify custom principal

---

index.js
package-lock.json
package.json

fix a bug where registering a space after authorizing as an email address with a + character in the first part would escape the + to %2B

fix: don't error when email address contains +

---

README.md
lib.js
test/helpers/env.js

previously, `w3` users would need to set 4 environment variables (`W3_ACCESS_SERVICE_DID`, `W3_ACCESS_SERVICE_URL`, `W3_UPLOAD_SERVICE_DID` and `W3_UPLOAD_SERVICE_URL`) to connect to staging or development services. 
This allows them to use 2 environment variables: `W3UP_SERVICE_DID` and `W3UP_SERVICE_URL`.

feat: introduce unified service config

---

README.md
bin.js
can.js
lib.js
test/bin.spec.js
test/lib.spec.js

adds impl, tests, and docs for the `can store rm` and `can upload rm` commands.
```shell
$ w3 can upload rm <root-cid>
$ w3 can store rm <car-cid>
```
License: MIT

feat: add `can store rm` & `can upload rm` commands

---

.github/actions/test/action.yml
.github/workflows/release.yml
.github/workflows/test.yml

> a verifiable way to link a package back to its source repository and the specific build instructions used to publish it.
- publish to npm with provenance flag
- update checkout and setup-node actions to v4
see: https://github.blog/2023-04-19-introducing-npm-package-provenance/
License: MIT

feat: add npm package provenance

---

README.md

Closes https://github.com/web3-storage/w3cli/issues/139

docs: update authorize to login

---

package-lock.json
package.json

18.0.6 introduced a bug by using `ArrayBuffer` instead of `Uint8Array`, which doesn't serialize to JSON cleanly. Pin it to 18.0.5 to avoid breaking existing clients.

fix: pin @web3-storage/access to 18.0.5

---

bin.js

The update notifier now specifies the global flag in the npm install advice as this is a cli.
```console
╭────────────────────────────────────────────────╮
│                                                │
│        Update available 7.0.0 → 7.0.3          │
│   Run npm i -g @web3-storage/w3cli to update   │
│                                                │
╰────────────────────────────────────────────────╯
```
before this change, it would encourage you to do a local install which is probably not what you want
License: MIT

fix: update notification includes -g flag for cli

---

index.js

Accessing via `'no-wrap'` does not work - it is ALWAYS `false` for some reason.
* If `--no-wrap` is passed, `options.wrap` will be `false`, otherwise `undefined`
* If `--wrap` is passed, `options.wrap` will be `true`
Also a tiny fix to ensure our store percentage cannot go over 100% (it can do because of CAR overhead).

fix: no-wrap option

---

README.md
bin.js
index.js
test/bin.spec.js

Print a new key pair. Does not change your current signing key.
Bring the feature from [`ucan-key`](https://github.com/olizilla/ucan-key) into w3cli
```shell
$ w3 key create
MgCZ5ftHm9e0FnNtFXA2sMZgcf97GO4vTaybGEfkBp/KR5+0BeZ44TKEOwUjbLqvFFs2hpFxD++IAEEL+3ySROyDsSRk=
$ w3 key create --json | jq
{
"did": "did:key:z6Mkt7urpgJKK38cEyB1uMGBzfdn6sZN2daB5pr75DZbgahZ",
"key": "MgCYj0pKJn5uf+4yr2DApB8idYtDY+9yhEYH64Po0uaj+R+0Byw7B8cSYrO4//5PqgWodYq8PMI/fSWZ1xdvdw15bmAw="
}
```
see: https://github.com/web3-storage/w3cli/issues/154#issuecomment-1885042715
License: MIT

feat: `w3 key create`

---

bin.js
test/bin.spec.js

Fix and test handling of `--wrap` option to `w3 up`
| flag         | result      |
|--------------|-------------|
| undefined    | wrap: true  |
| --wrap       | wrap: true  |
| --wrap true  | wrap: true  |
| --wrap=true  | wrap: true  |
| --wrap false | wrap: false |
| --wrap=false | wrap: false |
| --no-wrap    | wrap: false |
Also normalises the behaviour of other boolean flags to `w3 up` so we can set them like `w3 up --hidden=${{input.hidden}}` in scripts, where it would be fiddly to optionally include a flag. see: https://github.com/web3-storage/add-to-web3/pull/89/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R51
License: MIT

fix: make `w3 up --no-wrap` work as advertised.

---

index.js
package-lock.json
package.json
test/bin.spec.js

by simply relying on remove from client, we miss some feedback we were providing to the user on the CLI. We could add a `onShardDelete` to client to make it a bit better.  What do you think @alanshaw ?
Error testing for sharding is also now part of client and I removed tests here as they would also have expectations on output/

fix: use remove from client

---

README.md
bin.js
bridge.js
index.js
test/bin.spec.js

In service of the UCAN bridge implementation in https://github.com/web3-storage/w3infra/pull/325 this PR introduces a new `bridge generate-tokens` command that will generate values for the `X-Auth-Secret` and `Authorization` headers of the HTTP request users make to the bridge.

feat: introduce `bridge generate-tokens` command

---

README.md
bin.js
bridge.js

A few followups from feedback to https://github.com/web3-storage/w3cli/pull/175 :
- remove unused --output option
- add --json option
- clarify documentation

feat: updates from PR feedback

---

package.json

Addressing `npm ERR! 422 Unprocessable Entity - PUT https://registry.npmjs.org/@web3-storage%2fw3cli - Error verifying sigstore provenance bundle: Failed to validate repository information: package.json: "repository.url" is "git+https://github.com/web3-storage/w3cli.git", expected to match "https://github.com/w3s-project/w3cli" from provenance`.

fix: address npm provenance

---

can.js
index.js
lib.js
package-lock.json
package.json
test/helpers/context.js
test/helpers/env.js
test/helpers/http-server.js
test/helpers/random.js
test/helpers/receipt-http-server.js

Needs to wire a server to serve a receipt agent message so that we can finish the upload blob flow, given this uses a server also for storing data

chore: use w3up client final version

---

index.js
package-lock.json
package.json

We removed this from the client library (and use the JS native version) since there's a miriad of environments that JS runs in that have differing ways to load WASM. However in Node.js it's a captive environment so should load fine and give us a little speedup.

feat: use wasm piece hasher

---

index.js

Motivation:
* i found myself using `w3 proof ls` but wanting to know the audience of the proofs I'm seeing

feat: proof ls command shows proof aud

---

README.md

As conversation mantained in discord [here](https://discordapp.com/channels/1247475892435816553/1273237594985201816/1341772674875134032), `w3cli` tool will not work correctly when uploading multiple files and subfolder with the command `w3 up *`  when using node 18.x and 20.x. 
Works fie on node 22.x and 23.x , so changing requirement here.

fix: updated nodejs requirement

---

README.md
account.js

Now that email address is optional it's possible the user can type `w3 login` - in this case prompt for login method rather than error.

feat: prompt for login method
