storacha/w3cli

- bin.js
- index.js
- package-lock.json
- package.json
TODO: fix me
```
❯ ./bin.js space create foo
Created foo
file:///Users/oli/Code/web3-storage/w3cli/node_modules/@web3-storage/access/src/drivers/indexeddb.js:69
const openReq = indexedDB.open(this.#dbName, this.#dbVersion)
^
ReferenceError: indexedDB is not defined
at StoreIndexedDB.open (file:///Users/oli/Code/web3-storage/w3cli/node_modules/@web3-storage/access/src/drivers/indexeddb.js:69:21)
at #getOpenDB (file:///Users/oli/Code/web3-storage/w3cli/node_modules/@web3-storage/access/src/drivers/indexeddb.js:57:18)
at StoreIndexedDB.load (file:///Users/oli/Code/web3-storage/w3cli/node_modules/@web3-storage/access/src/drivers/indexeddb.js:119:37)
at create (file:///Users/oli/Code/web3-storage/w3cli/node_modules/@web3-storage/w3up-client/src/index.js:22:27)
at createSpace …
```
> feat: add `space` command with `create` and `register`

- package.json
For backwards compatibility...
> feat: add old CLI bin reference

- bin.js
- index.js
- lib.js
- package-lock.json
- package.json
A copy of the good work from here: https://github.com/web3-storage/web3.storage/blob/4d5a1a0e07db3c6749efed0072ab5b4c2fcb828e/packages/w3/index.js#L118-L163
> feat: up command

- README.md
> docs: add ToC links

- bin.js
- index.js
If you don't set this the UCANs expire immediately 🙈.
> fix: add expiration parameter

- README.md
- bin.js
- index.js
- package-lock.json
- package.json
- test/bin.spec.js
> feat: delegation ls and proof ls commands

- README.md
- bin.js
- index.js
- lib.js
- test/bin.spec.js
Similar to `space add` but doesn't also add the proof to your list of spaces.
> feat: add `proof add` command

- package-lock.json
- package.json
Need the DID fix in the w3up-client patch
License: MIT
Signed-off-by: Oli Evans <oli@protocol.ai>
> chore: update w3up-client to 4.0.1

- README.md
Closes #54 
TODO: Instructions for selecting NFT.Storage or web3.storage when registering provider
> feat: update README with new ToS

- README.md
- bin.js
- index.js
- test/bin.spec.js
this lets users figure out which providers a space is registered with
> feat: add `space info` command to w3cli

- package-lock.json
- package.json
we were depending on a bad version of @web3-storage/access, so bump it now that there's a fixed version
> fix: bump dependencies

- README.md
- package.json
release-please didn't release after a timeout-induced test failure. bump the test timeout and bump version to get it to release
> fix: raise test timeout and bump package version

- can.js
- index.js
- lib.js
- package-lock.json
- package.json
- shim.js
- test/bin.spec.js
- test/helpers/mocks.js
- test/helpers/ucanto.js
- test/lib.spec.js
- tsconfig.json
This PR fixes a bunch of linting issues and addes `tsc --noEmit` to the `lint` script so we stay on top of them.
> fix: various linting issues

- index.js
- lib.js
- package-lock.json
- package.json
This PR simply displays a nice human readable value for the shard size next to each shard:
> feat: display shard size

- package-lock.json
- package.json
Motivation:
* make use of https://github.com/web3-storage/w3up/pull/1047 and expect it to fix https://github.com/web3-storage/w3cli/issues/113
> feat: upgrade @web3-storage/access to 16.4.0 to fix bug with sessionProof selection with `w3 register space`

- bin.js
- can.js
- lib.js
- package-lock.json
- package.json
- test/bin.spec.js
Adds support for querying info for a given piece and get to know deals where it is present together with aggregate info. Note that I opted out of showing inclusion proof here as it would be bytes representation which probably would not make sense to show in my opinion. See outputs
No deals:
```sh
➜  w3cli git:(feat/can-filecoin-info) ✗ w3 can filecoin info bafkzcibcaycsfehfpywo35zgvilhaqegcsrslebar6vcnwvzi64fljvwdrhvqei
⠋ Getting filecoin info
Piece CID: bafkzcibcaycsfehfpywo35zgvilhaqegcsrslebar6vcnwvzi64fljvwdrhvqei
Deals: Piece being aggregated and offered for deal...
```
With deals:
```sh
➜  w3cli git:(feat/can-filecoin-info) ✗ w3 can filecoin info bafkzcibcaycsfehfpywo35zgvilhaqegcsrslebar6vcnwvzi64fljvwdrhvqei
Piece CID: bafkzcibcaycsfehfpywo35zgvilhaqegcsrslebar6vcnwvzi64fljvwdrhvqe …
```
> feat: can filecoin info

- package-lock.json
- package.json
this fixes https://github.com/web3-storage/w3cli/issues/143
> fix: upgrade to latest access-client

- account.js
Prevents:
```console
$ w3 login a@b.com
⁂ Agent was authorized by did:mailto:b.com:a
⠇ 🔗 please click the link sent to a@b.com to authorize this agent
```
> fix: clear timeout always

- account.js
- index.js
- added a function comment to trigger a release
> chore: migrate repo

- bridge.js
Need to trigger a full release to validate the NPM_TOKEN we're using.
> fix: remove leftover semicolon
